"""Классы для описания нод пайплайна."""

import abc
from typing import Any, Optional

from pipeline.object import Callback, Object, ObjectConstraint


class Node(abc.ABC):
    """Базовый класс для одной ноды пайплана."""

    def __init__(self, *, callback: str, input: list[str], output: Optional[ObjectConstraint]):
        """Базовый конструктор."""
        self.callback = callback
        self.input = input
        self.output = output

    @abc.abstractmethod
    def validate(self) -> None:
        """Валидирует ноду."""
        raise NotImplementedError

    def compute(self, func: Callback, inp: Object) -> Object:
        """Вычисляет ноду."""
        res = self._compute(func, inp)
        res.validate(self.output)
        return res

    @abc.abstractmethod
    def _compute(self, func: Callback, inp: Object) -> Object:
        """Реализация вычислений."""
        raise NotImplementedError


class NodeDbRead(Node):
    """Нода чтения из БД."""

    def validate(self) -> None:
        """Валидирует NodeDbRead."""
        if self.callback == "":
            raise ValueError("Callback for NodeDbRead cannot be empty")
        if self.output is None:
            raise ValueError("Output for NodeDbRead cannot be empty")

    def _compute(self, func: Callback, inp: Object) -> Object:
        """Читаем из БД."""
        return func(inp)


class NodeMerger(Node):
    """Нода объединения выходов других нод."""

    def validate(self) -> None:
        """Валидирует NodeMerger."""
        if self.callback != "":
            raise ValueError("Callback for NodeMerger is autogenerated")
        if len(self.input) == 0:
            raise ValueError("Input for NodeMerger cannot be empty")
        if self.output is not None:
            raise ValueError("Output for NodeMerger is autogenerated")

    def _compute(self, func: Callback, inp: Object) -> Object:
        """Объединяем входы."""
        return inp


class NodeAggregator(Node):
    """Обычная промежуточная нода."""

    def validate(self) -> None:
        """Валидирует NodeAggregator."""
        if self.callback == "":
            raise ValueError("Callback for NodeAggregator cannot be empty")
        if len(self.input) == 0:
            raise ValueError("Input for NodeAggregator cannot be empty")
        if self.output is None:
            raise ValueError("Output for NodeAggregator cannot be empty")

    def _compute(self, func: Callback, inp: Object) -> Object:
        """Выполняем пользовательский код."""
        return func(inp)


def node_type(name: str) -> type[Node]:
    """Получает тип ноды по строке."""
    match name:
        case "db_read":
            return NodeDbRead
        case "merger":
            return NodeMerger
        case "agg":
            return NodeAggregator
        case _:
            raise ValueError(f"Unknown value for PipelineNodeType: {name}")


def node_from_raw_cfg(raw_cfg: Any) -> Node:
    """Создаёт ноду из словаря."""
    assert isinstance(raw_cfg, dict), "Raw config for Node need be dict"
    node_cls = node_type(raw_cfg["type"])
    spec = node_cls(
        callback=raw_cfg.get("callback", ""),
        input=raw_cfg.get("input", []),
        output=ObjectConstraint.from_raw_cfg(raw_cfg.get("output", None)),
    )
    spec.validate()
    return spec
