"""Тесты на классы пайплайна."""

import pytest

from pipeline import Row, Table
from pipeline.node import NodeDbRead, NodeFunc, NodeMerge, node_from_raw_cfg, node_type
from pipeline.object import ObjectConstraint, object_type, primitive_type
from utils import read_from_yaml_str


def test_pipeline_object_primitive_type() -> None:
    """PrimitiveType конструируется из строки."""
    assert primitive_type("str") == str
    assert primitive_type("int") == int
    assert primitive_type("float") == float
    with pytest.raises(ValueError, match="Unknown value for PrimitiveType: dict"):
        primitive_type("dict")
    with pytest.raises(ValueError, match="Unknown value for PrimitiveType: "):
        primitive_type("")


def test_pipeline_object_type() -> None:
    """ObjectType конструируется из строки."""
    assert object_type("row") == Row
    assert object_type("table") == Table
    with pytest.raises(ValueError, match="Unknown value for ObjectType: other"):
        object_type("other")


def test_pipeline_object_type_constraint() -> None:
    """ObjectType конструируется из словарей и валидируется."""
    with pytest.raises(AssertionError, match="Raw config for ObjectConstraint need be dict"):
        ObjectConstraint.from_raw_cfg("hahaha")
    with pytest.raises(ValueError, match="Unknown value for ObjectType: no"):
        ObjectConstraint.from_raw_cfg({"type": "no"})
    with pytest.raises(AssertionError, match="ObjectConstraint.columns cannot be empty"):
        ObjectConstraint.from_raw_cfg({"type": "table"})
    with pytest.raises(AttributeError, match="'list' object has no attribute 'items'"):
        ObjectConstraint.from_raw_cfg({"type": "table", "columns": []})
    with pytest.raises(ValueError, match="Unknown value for PrimitiveType: no"):
        ObjectConstraint.from_raw_cfg({"type": "table", "columns": {"col1": "no"}})
    constraint = ObjectConstraint.from_raw_cfg(
        {"type": "table", "columns": {"col1": "int", "col2": "str", "col3": "float"}}
    )
    assert constraint is not None
    assert constraint.type == Table
    assert constraint.columns == {
        "col1": int,
        "col2": str,
        "col3": float,
    }


def test_pipeline_node_type() -> None:
    """PipelineNodeType конструируется из строки."""
    assert node_type("db_read") == NodeDbRead
    assert node_type("merge") == NodeMerge
    assert node_type("func") == NodeFunc
    with pytest.raises(ValueError, match="Unknown value for PipelineNodeType: do"):
        node_type("do")
    with pytest.raises(ValueError, match="Unknown value for PipelineNodeType: "):
        node_type("")


def test_pipeline_node_spec_db_read_ok() -> None:
    """NodeDbRead конструируется из словарей правильно."""
    spec = node_from_raw_cfg(
        read_from_yaml_str(
            """
type: db_read
callback: select_subjects_info_for_iti
input:
  - iti_id
output:
  type: table
  columns:
    subject_id: int
    about: str
"""
        ),
    )
    assert isinstance(spec, NodeDbRead)
    assert spec.callback == "select_subjects_info_for_iti"
    assert spec.input == ["iti_id"]
    assert spec.output == ObjectConstraint(
        type=Table,
        columns={
            "subject_id": int,
            "about": str,
        },
    )


def test_pipeline_node_db_spec_read_fail() -> None:  # noqa: CFQ001
    """NodeDbRead проверяет входы."""
    with pytest.raises(ValueError, match="Callback for NodeDbRead cannot be empty"):
        node_from_raw_cfg(
            read_from_yaml_str(
                """
type: db_read
input:
  - iti_id
output:
  type: table
  columns:
    subject_id: int
    about: str
"""
            ),
        )

    with pytest.raises(ValueError, match="Output for NodeDbRead cannot be empty"):
        node_from_raw_cfg(
            read_from_yaml_str(
                """
type: db_read
callback: select_subjects_info_for_iti
input:
  - iti_id
"""
            ),
        )


def test_pipeline_node_spec_merger_ok() -> None:
    """NodeMerge конструируется из словарей правильно."""
    spec = node_from_raw_cfg(
        read_from_yaml_str(
            """
type: merge
input:
  - math
  - rus
  - eng
"""
        ),
    )
    assert isinstance(spec, NodeMerge)
    assert spec.callback == ""
    assert spec.input == ["math", "rus", "eng"]
    assert spec.output is None


def test_pipeline_node_spec_merger_fail() -> None:
    """NodeMerge проверяет входы."""
    with pytest.raises(ValueError, match="Callback for NodeMerge is autogenerated"):
        node_from_raw_cfg(
            read_from_yaml_str(
                """
type: merge
callback: func
input:
  - math
  - rus
  - eng
"""
            ),
        )

    with pytest.raises(ValueError, match="Input for NodeMerge cannot be empty"):
        node_from_raw_cfg(
            read_from_yaml_str(
                """
type: merge
"""
            ),
        )

    with pytest.raises(ValueError, match="Output for NodeMerge is autogenerated"):
        node_from_raw_cfg(
            read_from_yaml_str(
                """
type: merge
input:
  - math
  - rus
  - eng
output:
  type: table
  columns:
    col: int
"""
            ),
        )


def test_pipeline_node_spec_agg_ok() -> None:
    """NodeFunc конструируется из словарей правильно."""
    spec = node_from_raw_cfg(
        read_from_yaml_str(
            """
type: func
callback: ind_agg_calc
input: [all_ind_res, db_iti_subjects]
output:
  type: table
  columns:
    student_id: int
    place: int
    total_score: float
"""
        ),
    )
    assert isinstance(spec, NodeFunc)
    assert spec.callback == "ind_agg_calc"
    assert spec.input == ["all_ind_res", "db_iti_subjects"]
    assert spec.output == ObjectConstraint(
        type=Table,
        columns={
            "student_id": int,
            "place": int,
            "total_score": float,
        },
    )


def test_pipeline_node_spec_agg_fail() -> None:  # noqa: CFQ001
    """NodeFunc проверяет входы."""
    with pytest.raises(ValueError, match="Callback for NodeFunc cannot be empty"):
        node_from_raw_cfg(
            read_from_yaml_str(
                """
type: func
input: [all_ind_res, db_iti_subjects]
output:
  type: table
  columns:
    student_id: int
    place: int
    total_score: float
"""
            ),
        )

    with pytest.raises(ValueError, match="Input for NodeFunc cannot be empty"):
        node_from_raw_cfg(
            read_from_yaml_str(
                """
type: func
callback: ind_agg_calc
output:
  type: table
  columns:
    student_id: int
    place: int
    total_score: float
"""
            ),
        )

    with pytest.raises(ValueError, match="Output for NodeFunc cannot be empty"):
        node_from_raw_cfg(
            read_from_yaml_str(
                """
type: func
callback: ind_agg_calc
input: [all_ind_res, db_iti_subjects]
"""
            ),
        )
