from .barcode import *
from .code import *
from .group_result import *
from .ind_day_student import *
from .iti import *
from .iti_subject import *
from .iti_subject_score import *
from .message import *
from .result import *
from .roles import *
from .school import *
from .student import *
from .student_class import *
from .student_eljur import *
from .subject import *
from .subject_student import *
from .super_game_result import *
from .team import *
from .team_consent import *
from .team_student import *
from .tg_user import *
from .user import *
