import backend.queries.simple
import backend.queries.help
import backend.queries.messages_help
import backend.queries.pages
import backend.queries.full
import backend.queries.auto_generator
import backend.queries.file_creator
import backend.queries.results
import backend.queries.students
import backend.queries.teams
import backend.queries.subjects
import backend.queries.barcodes
import backend.queries.codes
import backend.queries.excel
import backend.queries.phone_api
import backend.queries.bot_api
import backend.queries.scanner_web