import backend.queries.simple
import backend.queries.files_edit
import backend.queries.users
import backend.queries.help
import backend.queries.full
import backend.queries.auto_generator
import backend.queries.file_creator
import backend.queries.results
import backend.queries.students
